# -*- coding: utf-8 -*-
"""Variables.ipynb のコピー

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W695OGsLE_VrwW9JPdEI3ZmHd9Zwr6OZ

###Real-life analogy:

"Think of a locker in school or a gym. Each locker has a specific number, and inside, you can store your books, clothes, or other personal items. In programming, we have something similar called variables. Just like how you'd put your book in a locker and retrieve it later, in programming, we assign data to a variable and then use that variable to recall that data whenever we need it."

### **Definition and Purpose of Variables in Programming**

**Definition:**
In computer programming, a variable is a storage location paired with an associated symbolic name, which contains some known or unknown quantity of information referred to as a value.

**Purpose:**
Variables serve as a fundamental concept in programming, allowing developers to:
1. **Store Data:** Variables hold data that can be used and manipulated throughout a program.
2. **Improve Readability:** By using descriptive variable names, code becomes more readable and understandable.
3. **Facilitate Reuse:** Variables can be reused throughout different parts of a program, reducing redundancy.
4. **Change Behavior:** By changing a variable's value, the behavior of a program can be altered without changing its structure.

---

### **Naming Conventions and Rules**

**Naming Conventions:**
1. **Descriptive Names:** Variables should be named in a way that describes their content or use (e.g., `user_age` instead of `ua`).
2. **Camel Case:** Used mainly in languages like Java. E.g., `userName`.
3. **Snake Case:** Common in Python. E.g., `user_name`.
4. **Pascal Case:** Used for class names in many languages. E.g., `UserName`.

**Rules:**
1. Variable names must start with a letter (a-z, A-Z) or an underscore (_).
2. Subsequent characters can be letters, numbers, or underscores.
3. Variable names cannot be reserved words in the language (e.g., `if`, `else` in Python).
4. Variable names should not contain spaces.
5. Variable names are case-sensitive (`user` and `User` are different variables).

---

### **Assigning Values to Variables Using the Assignment Operator (=)**

In most programming languages, the equals sign (`=`) is used as the assignment operator. It assigns the value on its right to the variable on its left.

**Example:**
```python
age = 25
name = "John"
is_student = True
```

Here, the variable `age` is assigned a value of 25, the variable `name` is given the string "John", and the variable `is_student` is assigned a Boolean value of `True`.

---

### **Practice: Assign Various Values to Variables and Display Them**

**Task:** Create and assign values to three different variables: an integer, a string, and a boolean. Then, display them.

**Solution:**
```python
# Assigning values to variables
my_age = 30
my_name = "Alice"
likes_coffee = True

# Displaying the values
print("My age is:", my_age)
print("My name is:", my_name)
print("Do I like coffee?", likes_coffee)
```

When this program is run, it will display:
```
My age is: 30
My name is: Alice
Do I like coffee? True
```

---

# Exercise 1:

Declare variables for today's temperature, humidity percentage, and chance of rain.

Display a weather report: "Today's temperature is [temperature]°C with a humidity of [humidity]%. Chance of rain: [chance of rain]%."
"""

temp= 19
humi= 76
chance_of_rain= 5

print("Today's temperature is", temp, "℃ with a humidity of", humi, "%. Chance of rain:", chance_of_rain, "%")

"""# Exercise 2:

Grocery Receipt:

Pick three items you would buy from a grocery store.
Declare variables for each item's name and price.

Calculate and display the total bill.
"""

def mainmenu():
     #メインメニュー表示
     print("1.hamburger：$3　,\n""2.cheese hamburger：$3.5　,\n""3.fish hamburger：$3.25　,")
def drinkmenu():
     #ドリンクメニュー表示
     print("1.cola：$1　,\n""2.orange juice：$0.85　,\n""3.Green tea：$0.9")
def mainorder(a,b,c):
     #メインオーダーの注文取り
     n1=0;n2=0;n3=0;ko1=0;ko2=0;ko3=0
     mono=int(input("please type the number of you want＞＞＞"))
     if mono==1:
           ko1=kosuu()
           n1=a*ko1
     elif mono==2:
           ko2=kosuu()
           n2=b*ko2
     elif mono==3:
           ko3=kosuu()
           n3=c*ko3
     else:
           print("This number is not exist")
     return n1,n2,n3,ko1,ko2,ko3
def drinkorder(a,b,c):
     #ドリンクオーダーの注文取り
     n1=0;n2=0;n3=0;ko1=0;ko2=0;ko3=0
     mono=int(input("please type the number of you want＞＞＞"))
     if mono==1:
           ko1=kosuu()
           n1=a*ko1
     elif mono==2:
           ko2=kosuu()
           n2=b*ko2
     elif mono==3:
           ko3=kosuu()
           n3=c*ko3
     else:
           print("This number is not exist")
     return n1,n2,n3,ko1,ko2,ko3
def kosuu():
     #個数確認（メインとドリンク共通）
     kosuu=int(input("Type how many do you want＞＞＞"))
     return kosuu
def exit():
     #ご注文は以上ですかチェック
     ex=int(input("Do you prefer someting else\n"
                  "yes/1　no/2＞＞＞"))
     return ex
def drinkneed():
     #ドリンクもいるかチェック(１と２以外の数字で再問)
     drinkneed = int(input("Do you prefer some drink?\n"
                           "yes/１　no/２＞＞＞"))
     return drinkneed
#=====================【初期データ】========================================
#追加注文確認用フラグ
mexit=0;dexit=0
#商品の単価
m1p=3;m2p=3.5;m3p=3.25;d1p=1;d2p=0.85;d3p=0.9
#各商品の会計値段
m1n=0;m2n=0;m3n=0;d1n=0;d2n=0;d3n=0
#各商品の注文個数
m1ko=0;m2ko=0;m3ko=0;d1ko=0;d2ko=0;d3ko=0

#=====================【以下本体】=================================
#挨拶
print("Welcome to Grecery(?) store\n"
     "Please look at the menu and select a number\n")
#メインメニューの注文
while mexit<2:
     mainmenu()
     m1u,m2u,m3u,mk1u,mk2u,mk3u=mainorder(m1p,m2p,m3p)
     m1n=m1n+m1u;m2n=m2n+m2u;m3n=m3n+m3u
     m1ko=m1ko+mk1u;m2ko=m2ko+mk2u;m3ko=m3ko+mk3u
     mexit=exit()
#ドリンクメニューの注文
print("Your main food order confirmed")
dneed=drinkneed()
while dneed < 1 or dneed > 2:
     print("Please try again")
     dneed = drinkneed()
if dneed==1:
     print("Will going to show the drink menu.\n")
     while dexit<2:
           drinkmenu()
           d1u,d2u,d3u,d1ku,d2ku,d3ku=drinkorder(d1p,d2p,d3p)
           d1n=d1n+d1u;d2n=d2n+d2u;d3n=d3n+d3u
           d1ko=d1ko+d1ku;d2ko=d2ko+d2ku;d3ko=d3ko+d3ku
           dexit=exit()
else:
     print("Your order has been received.")
print("Your order has been received.\n")
#会計へ
if m1ko>0:
     print("hamburger：",m1ko)
if m2ko>0:
     print("cheese hamburger：",m2ko)
if m3ko>0:
     print("fish hamburger：",m3ko)
if d1ko>0:
     print("cola:",d1ko)
if d2ko>0:
     print("Orange juice:",d2ko)
if d3ko>0:
     print("Green tea",d3ko)
print("\n")
goukei=m1n+m2n+m3n+d1n+d2n+d3n
print("The price is $",goukei)
input("Press any key to finish")